backend:
  name: github
  repo: sydesignest2013/Web
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "portfolio"
    label: "Projekty Portfolio"
    folder: "data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa projektu", name: "title", widget: "string" }
      - { label: "Podtytuł", name: "subtitle", widget: "string" }
      - { label: "Kategoria", name: "category", widget: "select", options: ["Szaliki", "Koszulki", "Projektowanie"] }
      - { label: "Notka techniczna / opis", name: "description_note", widget: "text" }
      - { label: "Kolekcja Zdjęć", name: "images", widget: "list", field: { label: "Zdjęcie", name: "image", widget: "image" } }
